### ISSUE TITLE
13.2 TDOA定位 末段笔误

### ISSUE THREAD

**Issue by galaxy-tek** [iot-book/Comments#6]
值得注意的是，并非所有的通信信号及设备具备_纳米级_分辨率。比较典型的具备_纳米级_分辨率的信号时超宽带(Ultra-wideband, UWB)。UWB信号带宽大于500MHz。
================================
"纳米级分辨率"应该是纳秒的笔误。

**Comment by iot-book** [comment]
已修改，感谢指正
